name:                shaders
version:             0.1.0.0
github:              "mrehayden1/shaders"
license:             OtherLicense
author:              "Matthew Hayden"
maintainer:          "mrehayden@gmail.com"
copyright:           "2024 Matthew Hayden"

extra-source-files:
- README.md
- CHANGELOG.md

default-extensions:
- AllowAmbiguousTypes
- Arrows
- BinaryLiterals
- DataKinds
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeFamilies
- UndecidableInstances

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mrehayden1/shaders#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs:         src
  dependencies:
  - GLFW-b
  - binary
  - bytestring
  - containers
  - data-default
  - exception-transformers
  - hashtables
  - kan-extensions
  - language-spir-v
  - mtl
  - shaderc
  - time
  - transformers
  - utf8-string
  - vector
  - vulkan
  - witherable

executables:
  example:
    main:        Main.hs
    source-dirs: examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kan-extensions
    - mtl
    - shaders
    - time
